version: '3.9'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_HOSTNAME=$MONGO_INITDB_HOST
      - MONGO_PORT=$MONGO_INITDB_PORT
      - MONGO_DB=$MONGO_INITDB_DATABASE
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:27017 -- node server.js

  db:
    image: mongo
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
